### ISSUE TITLE
在hookfunction中调用原函数会闪退

### ISSUE THREAD

**Issue by mxsky01** [issuimo/HardBreakPointHook#1]
if (const auto pNClass = I::Get("Assembly-CSharp.dll")->Get("NGUIDebug", "*")) {
	
	mOnGUI = pNClass->Get<IM>("OnGUI")->Cast<void>();
}
if (mOnGUI) {
	
	SetBreakPoint(mOnGUI, HOnGUI);
}

 void HOnGUI()
{
     	return B::CallOrigin(HOnGUI);//到这一步游戏崩溃
        // B::CallOrigin(mOnGUI);  这样不崩溃，但不会调用原函数
}
hook之后能正常绘制内容，但调用原函数就会崩溃，是我什么地方出错了吗

**Comment by mxsky01** [comment]
`template<typename R, typename... Args>
static R CallOrigin(R(*func)(Args...), Args... args) {
	for (auto [fst, snd] : breakpoints) {
		
		if (snd.replacement == func) {
			R(*originalFunc)(Args...) = reinterpret_cast<R(*)(Args...)>(snd.original);
			R(*replacementFunc)(Args...) = reinterpret_cast<R(*)(Args...)>(snd.replacement);
			if constexpr (std::is_void_v<R>) {
				RemoveBreakPointThread(GetCurrentThread(), originalFunc);
				originalFunc(args...);
				SetBreakPointThread(GetCurrentThread(), originalFunc, replacementFunc);
				return;
			} else {
				RemoveBreakPointThread(GetCurrentThread(), originalFunc);
				R ret = originalFunc(args...);
				SetBreakPointThread(GetCurrentThread(), originalFunc, replacementFunc);
				return ret;
			}
		}
	}
	return R();
}`
崩溃应该是地址转方法实例的时候出错了，我改成这样就没问题了

**Comment by mxsky01** [comment]
static bool RemoveBreakPointThread(HANDLE hThread, R(*address)(Args...)) 中建议加个mutex锁，不然删除it的时候容易线程冲突而崩溃
现在还有一个问题就是我添加了三个断点hook，hook1自己执行的时候没问题，hook2执行了，hook1就会失效，hook3执行了，hook1,hook2都会失效，之后就只剩下hook3还生效，是因为没有单步进吗？该在什么地方改

**Comment by issuimo** [comment]
phmap::parallel_flat_hash_map是线程安全的不需要加锁

**Comment by issuimo** [comment]
对于失效问题，在代码不改动的情况下使用Intel C++ 2024编译，32位与64位均未发现此类问题，请考虑游戏自己做了手脚

**Comment by mxsky01** [comment]
> 对于失效问题，在代码不改动的情况下使用Intel C++ 2024编译，32位与64位均未发现此类问题，请考虑游戏自己做了手脚
找到问题了，在RemoveBreakPointThread中
CONTEXT ctx = { 0 };
这个出问题了，会让游戏崩溃，以及多个hook最后只剩下一个hook生效
在CONTEXT ctx = { 0 };前加一个mutex锁就解决问题

**Comment by mxsky01** [comment]
还有一个bug，代码
`if (breakpoints.size() < 4) {`
你本来设置的是4个断点，应该<5才对，<4就只能是3个断点了

**Comment by issuimo** [comment]
> 还有一个bug，代码 `if (breakpoints.size() < 4) {` 你本来设置的是4个断点，应该<5才对，<4就只能是3个断点了

这是正确的，只有小于4才有空的寄存器可用，如果等于4那么已经设置了4个寄存器的话依然会继续设置
